export type AdminEvent = {
  id: string;
  title: string;
  venueName: string | null;
  address: string | null;
  lat: number | null;
  lng: number | null;
  startAt: Date;
  endAt: Date | null;
  isFree: boolean | null;
  priceMin: number | null;
  priceMax: number | null;
  ticketUrl: string | null;
  sourceType: string;
  category: string | null;
  status: string | null;
  isVerified: boolean | null;
  confidenceScore: number | null;
  moreDates?: number;
};
